### ISSUE TITLE
composer-plugin-api dependency needs updating

### ISSUE THREAD

**Issue by ghost** [SimplyAdmire/ComposerPlugins#11]
I get the following error installing through composer 

> The "simplyadmire/composer-plugins" plugin was skipped because it requires a Plugin API version ("1.0.0") that does not match your Composer installation ("1.1.0"). You may need to run composer update with the "--no-plugins" option.

It looks like the requirement needs to be bumped.

**Comment by radmiraal** [comment]
changed it to ^1.0, hope it fixes it for you

**Comment by ghost** [comment]
Great, fixed thanks.
