### ISSUE TITLE
Remove deprecated "excludeClasses" setting

### ISSUE THREAD

**Issue by bwaidelich** [SimplyAdmire/ComposerPlugins#6]
With Flow 3.0, the "excludeClasses" setting will be deprecated (see https://review.typo3.org/36291).
`./flow configuration:validate` currently issues
```
Settings.TYPO3.Flow.object.excludeClasses -> This property is not allowed here, check the spelling if you think it belongs here.
```
on master.

I think the complete `Settings.yaml` file can be removed.

**Comment by radmiraal** [comment]
hey basti, thanks, got this on the radar indeed. Problem is that I rather have a deprecation warning for a while as just removing the file will include the package in reflection on Flow versions lower than 3.

I'm not yet sure how to fix this in a clean way, at least we should pull in an actual version of the typo3-ci/typo3flow package in the neos base distribution. That will make future switches a bit easier ;)

As the sniff pool package includes ~1.0 of this plugins package we could now remove this file, push it and tag version 2.0. And then we could overwrite the version number for the composer plugins in the base distributions composer.json.

Do you see a better / cleaner solution?

**Comment by radmiraal** [comment]
so... just for clarity

Neos base master requires "typo3-ci/typo3flow": "dev-master"
typo3-ci/typo3flow master requires "typo3-ci/typo3sniffpool": ">=1.0.0"
typo3-ci/typo3sniffpool 1.0.1 requires "simplyadmire/composer-plugins": "~1.0"

**Comment by bwaidelich** [comment]
The problem is, that the deprecation warning shows up in the Neos backend (see https://www.evernote.com/shard/s17/sh/7fd00c22-9575-4f23-bd98-37a7b6902e21/257276850530e519d797d361713a5047).
I think there's no other (clean) way other than tagging new versions and require them in the 3.0/master branch. If I see it right, this probably means a new `typo3-ci/typo3sniffpool` 2.0 and a `simplyadmire/composer-plugins` 2.0

**Comment by radmiraal** [comment]
I processed the other PR about installation on windows machines first, and tagged 1.0.3 with that fix in it. Now removed the configuration in master and tagged 2.0.0

**Comment by radmiraal** [comment]
I pushed https://review.typo3.org/#/c/37183/ which does not require any version requirement changes in the sniff packages, and prevents possible problems like this in the future.
